# Generated by Django 3.1.1 on 2020-11-23 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201122_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('tid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post'),
        ),
    ]
