# Generated by Django 3.1.1 on 2020-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201124_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher',
        ),
        migrations.AddField(
            model_name='post',
            name='teacher',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
