# Generated by Django 3.1.1 on 2020-11-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201124_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('tid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='teacher',
        ),
    ]
