# Generated by Django 3.1.1 on 2020-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201124_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='yes', max_length=60),
        ),
    ]
